# Generated by Django 3.2.9 on 2021-12-04 10:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Loan Paid to', 'Loan Paid to'), ('Loan Paid by', 'Loan Paid by'), ('Loan Gave to', 'Loan Gave to'), ('Loan Gave by', 'Loan Gave by')], max_length=20)),
                ('date', models.DateField(default=datetime.date(2021, 12, 4))),
                ('loan_time', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=10, message="Can't store less than 10.")])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
